name: x_place
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pin_code_fields: ^8.0.1
  carousel_slider: ^5.0.0
  lucide_icons: ^0.257.0
  url_launcher: ^6.0.9
  lottie: ^3.2.0
  readmore: ^3.0.0
  percent_indicator: ^4.2.5
  video_player: ^2.9.5
  chewie: ^1.11.3
  animated_bottom_navigation_bar: ^1.4.0
  overlapped_carousel: ^1.0.2
  get: ^4.7.2
  file_picker: ^10.1.9
  flutter_secure_storage: ^9.2.4
  dio: ^5.8.0+1
  fl_chart: ^1.0.0
  intl: ^0.20.2
  flutter_lints: ^5.0.0
  provider: ^6.1.5
  video_thumbnail: ^0.5.6
  flutter_markdown: ^0.7.7+1
  http: ^1.4.0
  audioplayers: ^6.4.0
  speech_to_text: ^7.0.0
  flutter_dotenv: ^5.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/appicon.png"
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/sliders/
    - assets/lottie/
    - assets/icons/
    - .env